spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_customer_db
    username: dayni
    password: 1024_Dayni
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081